server:
  port: "8080"
  host: "0.0.0.0"

openai:
  api_key: "" # Set via environment variable OPENAI_API_KEY
  embedding_model: "text-embedding-ada-002"
  completion_model: "gpt-3.5-turbo"
  max_completion_tokens: 1000
  temperature: 0.7

vectordb:
  type: "inmemory"
  dimension: 1536
  similarity_func: "cosine"
  max_results: 5

storage:
  document_dir: "./data/documents"
  db_path: "./data/gorag.db"